version: "3.9"

services:
  vitamins-backend:
    container_name: vitamins-backend
    build: ./
    dns:
      - 8.8.8.8
      - 8.8.4.4
    ports:
      - "8000:8000"
    restart: always
    entrypoint: /entrypoint.sh
    volumes:
      - ./:/vitamins-backend
      - static_volume:/vitamins-backend/staticfiles
    depends_on:
      - vitamins-db
    environment:
      - TZ=Asia/Bishkek
    networks:
      - vitamins_network

  telegram-bot:
    container_name: telegram-bot
    build: ./
    ports:
      - "8001:8001"
    restart: always
    entrypoint: /entrypoint_bot.sh
    volumes:
      - ./:/telegram-bot
    depends_on:
      - vitamins-db
    environment:
      - TZ=Asia/Bishkek
    networks:
      - vitamins_network

  vitamins-db:
    container_name: vitamins-db
    image: postgres:latest
    ports:
      - "5433:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data/
    env_file: .env
    networks:
      - vitamins_network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U vitamin_user -d vitamin_db"]
      interval: 10s
      timeout: 5s
      retries: 5

  redis:
    image: "redis:alpine"
    ports:
      - "6379:6379"
    networks:
      - vitamins_network
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5

networks:
  vitamins_network:
    driver: bridge

volumes:
  static_volume:
  pgdata: