version: "3.9"

services:
  vitamins-backend-test:
    container_name: vitamins-backend-test
    build:
      context: .
      network: host
    ports:
      - "8002:8000"
    restart: always
    entrypoint: /entrypoint.sh
    volumes:
      - ./:/vitamins-backend
      - static_volume_test:/vitamins-backend/staticfiles
    depends_on:
      - vitamins-db-test
    environment:
      - TZ=Asia/Bishkek

  vitamins-db-test:
    container_name: vitamins-db-test
    image: postgres:latest
    ports:
      - "5434:5432"
    volumes:
      - pgdata_test:/var/lib/postgresql/data/
    env_file: .env

volumes:
  static_volume_test:
  pgdata_test: